// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pasttgcwmictadsjrejd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBhc3R0Z2N3bWljdGFkc2pyZWpkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjU2Njk3MDUsImV4cCI6MjA4MTI0NTcwNX0.MkflxrxoVJiNArIvd_aRCIZsUIj77SdCFN1fKK-0djQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== 'undefined' ? localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  }
});